version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service

  user-service:
    build:
      context: ./user_service
    container_name: user-service
    ports:
      - "8080:8080"
